baseURL = 'https://purple-affogato.github.io/rtems-gsoc26/'
languageCode = 'en-us'
title = 'GSoC 2026 - RTEMS'
theme = 'risotto'

[menus]
	[[menus.main]]
		identifier = "posts"
		name = "Posts"
		url = "/posts"
		weight = 10

[params]
	subtitle = "purple-affogato's blog for GSoC 2026"
	[params.theme]
		palette = "tokyo-night-dark"
	[params.about]
		title = "GSoC 2026 - RTEMS Blog"
		description = "purple-affogato's blog for GSoC 2026"
		logo = "🐦‍⬛"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
